services:
  bot:
    image: github-tracker:$IMAGE_VERSION
    build:
      context: ./build
      args:
        PYTHON_VERSION: $PYTHON_VERSION
        UID: $UID
    container_name: github-tracker
    volumes:
      - ./app/bot.py:/app/bot.py:ro
      - ./app/release_db.py:/app/release_db.py:ro
      - ./app/config.json:/app/config.json:ro
      - ./storage:/var/lib/app
    restart: "no"
