services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-tracker
    container_name: github-tracker
    volumes:
      - ./app:/app:ro
      - ./storage:/var/lib/app
    restart: unless-stopped
