services:
  bot:
    image: github-tracker
    build:
      context: ./build
    container_name: github-tracker
    volumes:
      - ./app:/app:ro
      - ./storage:/var/lib/app
    restart: unless-stopped
